version: "3.7"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    container_name: lottery-postgres-db
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-postgres
    environment:
      - POSTGRES_DB=lotterydb
      - POSTGRES_USER=lottery
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-postgres:
